using Backend.Data.Database;
using Backend.Services.Rooms;
using Moq;
using Backend.Services.Desks;
using Microsoft.Extensions.Logging;

namespace Backend.Tests;

[Collection("Database collection")]
public class RoomServiceTests(DatabaseFixture fixture) : IAsyncLifetime
{
    private RoomService _roomService = null!;
    private Mock<IDeskControlService> _mockDeskControlService = null!;
    private Company _testCompany = null!;
    private Company _otherCompany = null!;
    private Room _testRoom = null!;

    public async Task InitializeAsync()
    {
        var logger = LoggerFactory.Create(builder => builder.AddConsole()).CreateLogger<RoomService>();
        _mockDeskControlService = new Mock<IDeskControlService>();
        _roomService = new RoomService(logger, fixture.DbContext, _mockDeskControlService.Object);

        // Setup test companies
        _testCompany = new Company
        {
            Id = Guid.NewGuid(),
            Name = "Test Company",
            UserMemberships = [],
            Rooms = [],
            SimulatorLink = null,
            SimulatorApiKey = null
        };

        _otherCompany = new Company
        {
            Id = Guid.NewGuid(),
            Name = "Other Company",
            UserMemberships = [],
            Rooms = [],
            SimulatorLink = null,
            SimulatorApiKey = null
        };

        _testRoom = new Room
        {
            Id = Guid.NewGuid(),
            DeskIds = [],
            CompanyId = _testCompany.Id,
            Company = _testCompany,
            Desks = [],
            OpeningHours = new OpeningHours
            {
                OpeningTime = new TimeOnly(8, 0),
                ClosingTime = new TimeOnly(17, 0),
                DaysOfTheWeek = DaysOfTheWeek.Monday | DaysOfTheWeek.Tuesday
            },
            ReadableId = "R-1"
        };

        fixture.DbContext.Companies.AddRange(_testCompany, _otherCompany);
        fixture.DbContext.Rooms.Add(_testRoom);
        await fixture.DbContext.SaveChangesAsync();
    }

    public Task DisposeAsync() => Task.CompletedTask;

    [Fact]
    public async Task GetAllRoomsAsync_ShouldReturnRoomsForCompany()
    {
        // Arrange
        var room2 = new Room
        {
            Id = Guid.NewGuid(),
            CompanyId = _testCompany.Id,
            Desks = [],
            OpeningHours = new OpeningHours(),
            ReadableId = "R-2"
        };
        fixture.DbContext.Rooms.Add(room2);
        await fixture.DbContext.SaveChangesAsync();

        // Act
        var result = await _roomService.GetAllRoomsAsync(_testCompany.Id);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(2, result.Count);
        Assert.All(result, r => Assert.Equal(_testCompany.Id, r.CompanyId));
    }

    [Fact]
    public async Task GetAllRoomsAsync_ShouldNotReturnRoomsFromOtherCompanies()
    {
        // Arrange
        var otherRoom = new Room
        {
            Id = Guid.NewGuid(),
            CompanyId = _otherCompany.Id,
            Desks = [],
            OpeningHours = new OpeningHours(),
            ReadableId = "R-1"
        };
        fixture.DbContext.Rooms.Add(otherRoom);
        await fixture.DbContext.SaveChangesAsync();

        // Act
        var result = await _roomService.GetAllRoomsAsync(_testCompany.Id);

        // Assert
        Assert.NotNull(result);
        Assert.DoesNotContain(result, r => r.Id == otherRoom.Id);
    }

    [Fact]
    public async Task GetRoomAsync_ShouldReturnRoom_WhenExists()
    {
        // Act
        var result = await _roomService.GetRoomAsync(_testCompany.Id, _testRoom.Id);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(_testRoom.Id, result.Id);
        Assert.Equal(_testCompany.Id, result.CompanyId);
        Assert.NotNull(result.Desks);
    }

    [Fact]
    public async Task GetRoomAsync_ShouldReturnNull_WhenNotExists()
    {
        // Arrange
        var nonExistentId = Guid.NewGuid();

        // Act
        var result = await _roomService.GetRoomAsync(_testCompany.Id, nonExistentId);

        // Assert
        Assert.Null(result);
    }

    [Fact]
    public async Task GetRoomAsync_ShouldReturnNull_WhenRoomBelongsToOtherCompany()
    {
        // Act
        var result = await _roomService.GetRoomAsync(_otherCompany.Id, _testRoom.Id);

        // Assert
        Assert.Null(result);
    }

    [Fact]
    public async Task CreateRoomAsync_ShouldCreateRoom_WithAutoGeneratedReadableId()
    {
        // Arrange
        var newRoom = new Room
        {
            DeskIds = [],
            Desks = [],
            OpeningHours = new OpeningHours()
        };

        // Act
        var result = await _roomService.CreateRoomAsync(_testCompany.Id, newRoom);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(_testCompany.Id, result.CompanyId);
        Assert.NotNull(result.ReadableId);
        Assert.StartsWith("R-", result.ReadableId);
        
        var created = await fixture.DbContext.Rooms.FindAsync(result.Id);
        Assert.NotNull(created);
    }

    [Fact]
    public async Task CreateRoomAsync_ShouldIncrementReadableId()
    {
        // Arrange
        var room2 = new Room
        {
            DeskIds = [],
            Desks = [],
            OpeningHours = new OpeningHours()
        };

        // Act
        var result = await _roomService.CreateRoomAsync(_testCompany.Id, room2);

        // Assert
        Assert.NotNull(result);
        Assert.Equal("R-2", result.ReadableId);
    }

    [Fact]
    public async Task UpdateRoomAsync_ShouldUpdateRoom_WhenExists()
    {
        // Arrange
        var updatedRoom = new Room
        {
            DeskIds = [Guid.NewGuid()],
            OpeningHours = new OpeningHours
            {
                OpeningTime = new TimeOnly(9, 0),
                ClosingTime = new TimeOnly(18, 0),
                DaysOfTheWeek = DaysOfTheWeek.Monday
            }
        };

        // Act
        var result = await _roomService.UpdateRoomAsync(_testCompany.Id, _testRoom.Id, updatedRoom);

        // Assert
        Assert.True(result);
        var updated = await fixture.DbContext.Rooms.FindAsync(_testRoom.Id);
        Assert.NotNull(updated);
        Assert.Single(updated.DeskIds);
        Assert.Equal(new TimeOnly(9, 0), updated.OpeningHours.OpeningTime);
    }

    [Fact]
    public async Task UpdateRoomAsync_ShouldReturnFalse_WhenNotExists()
    {
        // Arrange
        var nonExistentId = Guid.NewGuid();
        var updatedRoom = new Room
        {
            DeskIds = [],
            OpeningHours = new OpeningHours()
        };

        // Act
        var result = await _roomService.UpdateRoomAsync(_testCompany.Id, nonExistentId, updatedRoom);

        // Assert
        Assert.False(result);
    }

    [Fact]
    public async Task DeleteRoomAsync_ShouldDeleteRoom_WhenExists()
    {
        // Arrange
        var roomToDelete = new Room
        {
            Id = Guid.NewGuid(),
            CompanyId = _testCompany.Id,
            Desks = [],
            OpeningHours = new OpeningHours(),
            ReadableId = "R-99"
        };
        fixture.DbContext.Rooms.Add(roomToDelete);
        await fixture.DbContext.SaveChangesAsync();

        // Act
        var result = await _roomService.DeleteRoomAsync(_testCompany.Id, roomToDelete.Id);

        // Assert
        Assert.True(result);
        var deleted = await fixture.DbContext.Rooms.FindAsync(roomToDelete.Id);
        Assert.Null(deleted);
    }

    [Fact]
    public async Task DeleteRoomAsync_ShouldReturnFalse_WhenNotExists()
    {
        // Arrange
        var nonExistentId = Guid.NewGuid();

        // Act
        var result = await _roomService.DeleteRoomAsync(_testCompany.Id, nonExistentId);

        // Assert
        Assert.False(result);
    }

    [Fact]
    public async Task SetRoomHeightAsync_ShouldCallDeskControlService_WhenRoomExists()
    {
        // Arrange
        var newHeight = 100;
        _mockDeskControlService
            .Setup(x => x.SetRoomDesksHeightAsync(_testRoom.Id, newHeight))
            .ReturnsAsync(true);

        // Act
        var result = await _roomService.SetRoomHeightAsync(_testCompany.Id, _testRoom.Id, newHeight);

        // Assert
        Assert.True(result);
        _mockDeskControlService.Verify(
            x => x.SetRoomDesksHeightAsync(_testRoom.Id, newHeight),
            Times.Once);
    }

    [Fact]
    public async Task SetRoomHeightAsync_ShouldReturnFalse_WhenRoomNotExists()
    {
        // Arrange
        var nonExistentId = Guid.NewGuid();
        var newHeight = 100;

        // Act
        var result = await _roomService.SetRoomHeightAsync(_testCompany.Id, nonExistentId, newHeight);

        // Assert
        Assert.False(result);
        _mockDeskControlService.Verify(
            x => x.SetRoomDesksHeightAsync(It.IsAny<Guid>(), It.IsAny<int>()),
            Times.Never);
    }

    [Fact]
    public async Task SetRoomHeightAsync_ShouldReturnDeskControlServiceResult()
    {
        // Arrange
        var newHeight = 100;
        _mockDeskControlService
            .Setup(x => x.SetRoomDesksHeightAsync(_testRoom.Id, newHeight))
            .ReturnsAsync(false);

        // Act
        var result = await _roomService.SetRoomHeightAsync(_testCompany.Id, _testRoom.Id, newHeight);

        // Assert
        Assert.False(result);
    }
}
